# Use an official Python runtime as a parent image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Set the working directory in the container
WORKDIR /ITcompany

# Copy the requirements file into the container at /app
COPY requirements.txt /ITcompany/

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /ITcompany/

# Copy the environment file into the container at /app
COPY .env /ITcompany/

# Expose port 8000 to the outside world
EXPOSE 8000